name: Deploy MkDocs site to GitHub Pages

on:
  push:
    branches:
      - main
  # 手動実行も可能にする
  workflow_dispatch:

# gh-pages ブランチへ push するための権限
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ hashFiles('requirements.txt') }}
          path: ~/.cache/pip
          restore-keys: |
            mkdocs-material-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build and deploy to gh-pages
        run: mkdocs gh-deploy --force --clean
